let listaPalavras = [
    ["GATO", "ANIMAL"],
    ["CACHORRO", "ANIMAL"],
    ["CAVALO", "ANIMAL"],
    ["TATU", "ANIMAL"],
    ["GAIVOTA", "ANIMAL"],
    ["PAVAO", "ANIMAL"],
    ["MACACO", "ANIMAL"],
    ["RATO", "ANIMAL"],
    ["PAPAGAIO", "ANIMAL"],
    ["JAVALI", "ANIMAL"], 
    ["RINOCERONTE", "ANIMAL"],
    ["FALCAO", "ANIMAL"],
    ["MOSCA", "ANIMAL"],
    ["GUEPARDO", "ANIMAL"],
    ["ELEFANTE", "ANIMAL"],
    ["GIRAFA", "ANIMAL"],
    ["ZEBRA", "ANIMAL"],
    ["URSO", "ANIMAL"],
    ["ORNITORRINCO", "ANIMAL"],
    ["ONÇA", "ANIMAL"],
    ["PREGUIÇA", "ANIMAL"],

    ["ADVOGADO", "PROFISSÃO"],
    ["ENFERMEIRA", "PROFISSÃO"],
    ["PROGRAMADOR", "PROFISSÃO"],
    ["DESIGNER", "PROFISSÃO"],
    ["TATUADOR", "PROFISSÃO"],
    ["PINTOR", "PROFISSÃO"],
    ["ANESTESISTA", "PROFISSÃO"],
    ["ENGENHEIRO", "PROFISSÃO"],
    ["MOTORISTA", "PROFISSÃO"],
    ["PAISAGISTA", "PROFISSÃO"],
    ["MANICURE", "PROFISSÃO"],
    ["COSTUREIRA", "PROFISSÃO"],
    ["REDATOR", "PROFISSÃO"],
    ["ATENDENTE", "PROFISSÃO"],
    ["AGRICULTOR", "PROFISSÃO"],
    ["PORTEIRO", "PROFISSÃO"],
    ["ZELADOR", "PROFISSÃO"],
    ["FAXINEIRO", "PROFISSÃO"],

    ["PIANO", "INSTRUMENTO MUSICAL"],
    ["TECLADO", "INSTRUMENTO MUSICAL"],
    ["TROMPETE", "INSTRUMENTO MUSICAL"],
    ["VIOLINO", "INSTRUMENTO MUSICAL"],
    ["VIOLAO", "INSTRUMENTO MUSICAL"],
    ["GUITARRA", "INSTRUMENTO MUSICAL"],
    ["BAIXO", "INSTRUMENTO MUSICAL"],
    ["BATERIA", "INSTRUMENTO MUSICAL"],
    ["HARPA", "INSTRUMENTO MUSICAL"],
    ["BERIMBAU", "INSTRUMENTO MUSICAL"],
    ["XILOFONE", "INSTRUMENTO MUSICAL"],

    ["FUTEBOL", "ESPORTE"],
    ["BASQUETE", "ESPORTE"],
    ["VOLEI", "ESPORTE"],
    ["CANOAGEM", "ESPORTE"],
    ["ESGRIMA", "ESPORTE"],
    ["JUDO", "ESPORTE"],
    ["HANDEBOL", "ESPORTE"],
    ["TENIS", "ESPORTE"],
    ["CICLISMO", "ESPORTE"],
    ["ATLETISMO", "ESPORTE"],
    ["NATAÇAO", "ESPORTE"],
    ["XADREZ", "ESPORTE"],

    ["COMPUTADOR", "OBJETO"],
    ["MESA", "OBJETO"],
    ["MICROONDAS", "OBJETO"],
    ["VENTILADOR", "OBJETO"],
    ["TAPETE", "OBJETO"],
    ["PORTA", "OBJETO"],
    ["PRATELEIRA", "OBJETO"],
    ["COLHER", "OBJETO"],
    ["CAFETEIRA", "OBJETO"],
    ["VARAL", "OBJETO"],
    ["CORTINA", "OBJETO"],
    ["VASSOURA", "OBJETO"],
    ["AIRFRAYER", "OBJETO"],
    ["CELULAR", "OBJETO"],
    ["SMARTPHONE", "OBJETO"],
    ["GARFO", "OBJETO"],
    ["CHINELO", "OBJETO"],
    ["AZULEJO", "OBJETO"],
    ["PAPIRO", "OBJETO"],

    ["BRASIL", "LUGARES"],
    ["MARANHAO", "LUGARES"],
    ["BLUMENAU", "LUGARES"],
    ["FRANÇA", "LUGARES"],
    ["PERNAMBUCO", "LUGARES"],
    ["JAMAICA", "LUGARES"],
    ["PERU", "LUGARES"],
    ["GRAJAU", "LUGARES"],
    ["CATUMBI", "LUGARES"],
    ["CATETE", "LUGARES"],
    ["GOIANIA", "LUGARES"],
    ["PORTUGAL", "LUGARES"],
    ["FINLANDIA", "LUGARES"],
    ["SUIÇA", "LUGARES"],
    ["SUECIA", "LUGARES"],
    ["GROELANDIA", "LUGARES"],
    ["ESPANHA", "LUGARES"],
    
    ["VASCO", "TIME"],
    ["FLAMENGO", "TIME"],
    ["BOTAFOGO", "TIME"],
    ["FLUMINENSE", "TIME"],
    ["JUVENTUS", "TIME"],
    ["PORTUGUESA", "TIME"],
    ["SPORT", "TIME"],
    ["SANTOS", "TIME"],
    ["PALMEIRAS", "TIME"],
    ["CHAPECOENSE", "TIME"],
    ["CHELSEA", "TIME"],
    ["BARCELONA", "TIME"],
    ["CHELSEA", "TIME"],
    ["LIVERPOOL", "TIME"],
    ["ARSENAL", "TIME"],
    ["MILAN", "TIME"],

    ["AÇUCAR", "COMIDA"],
    ["AÇAFRAO", "COMIDA"],
    ["AÇAI", "COMIDA"],
    ["PAÇOCA", "COMIDA"],
    ["LASANHA", "COMIDA"],
    ["STROGONOFF", "COMIDA"],
    ["FAROFA", "COMIDA"],
    ["BOLO", "COMIDA"],
    ["SALADA", "COMIDA"],
    ["LAMEM", "COMIDA"],
    ["SUSHI", "COMIDA"],
    ["COXINHA", "COMIDA"],
    ["FEIJOADA", "COMIDA"],

    ["CARAMBOLA", "FRUTA"],
    ["JACA", "FRUTA"],
    ["ACEROLA", "FRUTA"],
    ["ABACATE", "FRUTA"],
    ["MELANCIA", "FRUTA"],
    ["ABACAXI", "FRUTA"],
    ["MAÇA", "FRUTA"],
    ["AMEIXA", "FRUTA"],
    ["JABUTICABA", "FRUTA"],
    ["JAMBO", "FRUTA"],
    ["FIGO", "FRUTA"],
    ["AMORA", "FRUTA"],
    ["CEREJA", "FRUTA"],

    ["INSTAGRAM", "INTERNET"],
    ["FACEBOOK", "INTERNET"],
    ["WHATSAPP", "INTERNET"],
    ["GOOGLE", "INTERNET"],
    ["YOUTUBE", "INTERNET"],
];